<?php

return [
    'meeting_options' => range(1, 14),

    'material_options' => [
        'Pengantar Pemrograman Visual Dan Pengenalan Visual Studio 12',
        'OOP (Object Oriented Programing)',
        'OOP (Object Oriented Programing) - Lanjutan',
        'UI dan UX dengan Visual Studio 2012 (Case : Program Kasir Sederhana)',
        'Project Program Kasir Sederhana (Class dan Coding)',
        'Project Program Kasir - Pengembangan',
        'Project Program Kasir - Pengembangan Lanjutan',
        'Database (MySQL)',
        'Koneksi Database',
        'Contoh Kasus Aplikasi Perpustakaan (Desain UI/UX)',
        'Studi Kasus Aplikasi Perpustakaan Lanjutan (Coding)',
        'Studi Kasus Aplikasi Perpustakaan Lanjutan (Desain Laporan)',
        'Studi Kasus Aplikasi Penjualan',
        'Studi Kasus Aplikasi Penjualan Lanjutan (Coding dan Hasil)',
    ],

    'default_project' => [
        'pertemuan_ke' => 5,
        'materi' => 'Project Program Kasir Sederhana (Class dan Coding)',
        'nama_proyek' => 'Aplikasi Kasir Sederhana',
        'deskripsi' => 'Aplikasi kasir berbasis GUI untuk membantu UMKM mencatat transaksi, mengelola produk, dan menyusun laporan penjualan secara lebih efisien.',
    ],

    'demo_progress' => [
        'B' => 'selesai',
        'A' => 'selesai',
        'D' => 'proses',
        'R' => 'belum',
        'U' => 'belum',
        'L' => 'belum',
    ],

    'demo_reflection' => 'Saya mulai memahami bahwa keberhasilan proyek tidak hanya ditentukan oleh coding, tetapi juga oleh kejelasan masalah, struktur data, dan evaluasi bertahap pada setiap sintak BADRUL.',

    'help_cards' => [
        [
            'title' => 'Ikuti Sintak Secara Berurutan',
            'description' => 'Mulai dari perumusan masalah, lanjut ke analisis, pengembangan, revisi, presentasi, lalu refleksi. Setiap tahap menyimpan bukti kerja mahasiswa.',
        ],
        [
            'title' => 'Gunakan AI Sebagai Pendamping',
            'description' => 'AILS memberi prompt, pertanyaan penuntun, dan ide perbaikan di setiap sintak. Gunakan untuk memperjelas keputusan, bukan menggantikan proses belajar.',
        ],
        [
            'title' => 'Pantau Learning Analytics',
            'description' => 'Progress sintak, keterisian workspace, dan refleksi akhir menjadi indikator perkembangan proyek serta pemahaman mahasiswa.',
        ],
    ],

    'stages' => [
        'B' => [
            'order' => 1,
            'title' => 'Begin With Big Question',
            'summary' => 'Memulai dengan pertanyaan mendasar',
            'description' => 'Tahap ini menegaskan masalah nyata, pertanyaan inti proyek, dan target solusi yang ingin dicapai mahasiswa.',
            'workspace_title' => 'Ruang Kerja Proyek: Begin With Big Question (B)',
            'workspace_intro' => 'Jelajahi masalah yang relevan dan rumuskan pertanyaan mendasar untuk memulai proyek.',
            'color' => '#1d5ff2',
            'fields' => [
                [
                    'name' => 'nama_proyek',
                    'label' => 'Nama Proyek *',
                    'type' => 'text',
                    'required' => true,
                    'project_attribute' => 'nama_proyek',
                    'persist_to_workspace' => false,
                    'placeholder' => 'Tuliskan nama proyek Anda...',
                ],
                [
                    'name' => 'masalah_nyata',
                    'label' => 'Permasalahan Nyata *',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'Jelaskan masalah nyata yang ingin diselesaikan melalui proyek ini...',
                ],
                [
                    'name' => 'pertanyaan_mendasar',
                    'label' => 'Big Question (Pertanyaan Mendasar) *',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'Rumuskan pertanyaan inti yang akan dijawab oleh proyek ini...',
                ],
                [
                    'name' => 'ide_solusi_awal',
                    'label' => 'Ide Solusi Awal',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Tuliskan gambaran awal solusi yang ingin Anda buat...',
                ],
                [
                    'name' => 'tujuan_proyek',
                    'label' => 'Tujuan Proyek',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Tuliskan tujuan proyek yang ingin dicapai...',
                ],
                [
                    'name' => 'catatan_tambahan',
                    'label' => 'Catatan Tambahan (Opsional)',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Tuliskan catatan tambahan terkait tahap ini...',
                ],
            ],
            'demo_payload' => [
                'pertanyaan_mendasar' => 'Bagaimana cara merancang aplikasi kasir sederhana yang membantu UMKM mencatat transaksi dengan mudah, cepat, dan akurat?',
                'masalah_nyata' => 'Pencatatan transaksi UMKM masih dilakukan secara manual sehingga rawan kesalahan, sulit direkap, dan lambat saat dibutuhkan untuk laporan.',
                'ide_solusi_awal' => 'Membuat aplikasi kasir desktop sederhana dengan alur transaksi cepat, pengelolaan produk, dan rekap penjualan harian.',
                'tujuan_proyek' => 'Membangun aplikasi kasir sederhana berbasis GUI yang dapat digunakan untuk mencatat transaksi penjualan, menyimpan data produk, dan menampilkan ringkasan laporan.',
                'catatan_tambahan' => 'Fokus awal proyek adalah kemudahan penggunaan untuk kasir pemula dan pemilik usaha kecil.',
            ],
            'assistants' => [
                [
                    'name' => 'AI Reasoning Assistant',
                    'description' => 'Bantuan analisis masalah & pertanyaan mendasar.',
                    'prompt' => 'Untuk proyek :nama_proyek pada sintak Begin With Big Question, bantu saya menganalisis masalah inti, memperjelas pertanyaan mendasar, dan menilai apakah ruang lingkup proyek sudah realistis untuk materi :materi.',
                    'default_extra_context' => 'Bantu saya menganalisis permasalahan utama dari proyek yang akan dikembangkan serta membantu merumuskan pertanyaan mendasar proyek secara logis dan relevan dengan mata kuliah Pemrograman Visual.',
                ],
                [
                    'name' => 'AI Idea Assistant',
                    'description' => 'Bantuan ide proyek & solusi kreatif.',
                    'prompt' => 'Untuk proyek :nama_proyek, bantu saya menghasilkan beberapa ide solusi kreatif yang tetap realistis, jelaskan kelebihan tiap ide, lalu rekomendasikan opsi terbaik berdasarkan konteks proyek ini: :deskripsi.',
                    'default_extra_context' => 'Berikan ide proyek aplikasi berbasis Pemrograman Visual beserta fitur utama yang sesuai dengan kebutuhan pengguna dan dapat diselesaikan pada proyek perkuliahan.',
                ],
            ],
        ],
        'A' => [
            'order' => 2,
            'title' => 'Analyze and Plan',
            'summary' => 'Menganalisis dan merencanakan',
            'description' => 'Mahasiswa menyusun kebutuhan pengguna, alur kerja aplikasi, serta rencana pengembangan sebagai dasar implementasi.',
            'workspace_title' => 'Ruang Kerja Proyek: Analyze and Plan (A)',
            'workspace_intro' => 'Lakukan analisis kebutuhan dan rencanakan langkah-langkah proyek.',
            'color' => '#16a067',
            'fields' => [
                [
                    'name' => 'analisis_kebutuhan_pengguna',
                    'label' => 'Analisis Kebutuhan Pengguna *',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'Jelaskan hasil analisis kebutuhan pengguna untuk proyek ini...',
                ],
                [
                    'name' => 'fitur_aplikasi',
                    'label' => 'Fitur Aplikasi *',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'Daftarkan fitur aplikasi yang akan dibangun...',
                ],
                [
                    'name' => 'tools_software',
                    'label' => 'Tools/Software yang Digunakan',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Tuliskan tools atau software yang akan digunakan...',
                ],
                [
                    'name' => 'timeline_proyek',
                    'label' => 'Time Line Proyek *',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'Susun urutan waktu atau tahapan pengerjaan proyek...',
                ],
                [
                    'name' => 'pembagian_tugas',
                    'label' => 'Pembagian Tugas (Kelompok)',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Jelaskan pembagian tugas tiap anggota kelompok jika ada...',
                ],
                [
                    'name' => 'catatan_tambahan',
                    'label' => 'Catatan Tambahan (Opsional)',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Tuliskan catatan tambahan terkait tahap ini...',
                ],
            ],
            'demo_payload' => [
                'analisis_kebutuhan_pengguna' => 'Pengguna membutuhkan alur transaksi yang cepat, tampilan sederhana, dan laporan penjualan yang mudah dipahami.',
                'fitur_aplikasi' => 'Login admin, pengelolaan data produk, transaksi penjualan, perhitungan total otomatis, dan laporan penjualan.',
                'tools_software' => 'Visual Studio 2012, MySQL, XAMPP, dan Git untuk pengelolaan versi.',
                'timeline_proyek' => 'Minggu 1 analisis kebutuhan, minggu 2 desain UI, minggu 3 implementasi modul inti, minggu 4 pengujian.',
                'pembagian_tugas' => 'Anggota 1 menangani desain form, anggota 2 menangani database, anggota 3 menangani laporan dan pengujian.',
                'catatan_tambahan' => 'Perlu sinkronisasi rutin antar anggota agar integrasi modul tetap lancar.',
            ],
            'assistants' => [
                [
                    'name' => 'AI Planning Assistant',
                    'description' => 'Bantuan penyusunan rencana proyek.',
                    'prompt' => 'Untuk proyek :nama_proyek pada sintak Analyze and Plan, bantu saya menyusun rencana kerja proyek yang runtut, prioritas pengerjaan, dan checkpoint utama yang realistis.',
                    'default_extra_context' => 'Bantu saya menyusun rencana pengembangan proyek aplikasi secara sistematis mulai dari analisis kebutuhan, perancangan, implementasi, hingga pengujian aplikasi.',
                ],
                [
                    'name' => 'AI Learning Resource Assistant',
                    'description' => 'Bantuan rekomendasi sumber belajar.',
                    'prompt' => 'Untuk proyek :nama_proyek dan materi :materi, rekomendasikan sumber belajar, topik yang perlu dipelajari, dan urutan belajar yang paling membantu untuk tahap analisis dan perencanaan.',
                    'default_extra_context' => 'Berikan rekomendasi sumber belajar, tutorial, referensi kode, dan materi yang relevan untuk membantu pengembangan proyek aplikasi berbasis Pemrograman Visual.',
                ],
                [
                    'name' => 'AI Requirement Analysis Assistant',
                    'description' => 'Bantuan analisis kebutuhan sistem.',
                    'prompt' => 'Untuk proyek :nama_proyek, bantu saya menganalisis kebutuhan sistem dengan merinci kebutuhan pengguna, kebutuhan fungsional, kebutuhan nonfungsional, dan asumsi penting proyek.',
                    'default_extra_context' => 'Bantu saya menganalisis kebutuhan sistem dan kebutuhan pengguna untuk proyek aplikasi yang akan dikembangkan, termasuk fitur utama, input, proses, dan output aplikasi.',
                ],
            ],
        ],
        'D' => [
            'order' => 3,
            'title' => 'Design and Develop',
            'summary' => 'Merancang dan mengembangkan',
            'description' => 'Tahap pengembangan antarmuka, struktur data, dan implementasi program sesuai rencana yang telah dibuat.',
            'workspace_title' => 'Ruang Kerja Proyek: Design and Develop (D)',
            'workspace_intro' => 'Rancang antarmuka, bangun database, dan kembangkan kode program.',
            'color' => '#ff6b00',
            'fields' => [
                [
                    'name' => 'nama_proyek',
                    'label' => 'Nama Proyek *',
                    'type' => 'text',
                    'required' => true,
                    'project_attribute' => 'nama_proyek',
                    'persist_to_workspace' => false,
                    'placeholder' => 'Tuliskan nama proyek Anda...',
                ],
                [
                    'name' => 'deskripsi',
                    'label' => 'Deskripsi Proyek *',
                    'type' => 'textarea',
                    'required' => true,
                    'project_attribute' => 'deskripsi',
                    'persist_to_workspace' => false,
                    'placeholder' => 'Jelaskan deskripsi proyek yang sedang Anda kembangkan...',
                ],
                [
                    'name' => 'desain_gui',
                    'label' => 'Desain GUI',
                    'type' => 'file',
                    'required' => false,
                    'helper' => 'Upload / Pilih File Desain (Opsional)',
                ],
                [
                    'name' => 'struktur_database',
                    'label' => 'Struktur Database',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Uraikan tabel, field, dan relasi database yang digunakan...',
                ],
                [
                    'name' => 'kode_program',
                    'label' => 'Kode Program',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Jelaskan bagian kode atau modul yang sedang dikembangkan...',
                ],
                [
                    'name' => 'kendala_pengembangan',
                    'label' => 'Kendala Pengembangan',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Tuliskan kendala yang dihadapi saat proses pengembangan...',
                ],
                [
                    'name' => 'lampiran_file',
                    'label' => 'Upload File (Opsional)',
                    'type' => 'file',
                    'required' => false,
                ],
            ],
            'demo_payload' => [
                'struktur_database' => 'Database MySQL menggunakan tabel users, produk, transaksi, dan detail_transaksi. Relasi utama: satu transaksi memiliki banyak detail_transaksi.',
                'kode_program' => 'Modul yang sedang dikembangkan mencakup form transaksi, proses simpan data, dan validasi input nominal serta stok.',
                'kendala_pengembangan' => 'Sinkronisasi antara desain form, struktur tabel, dan proses perhitungan total transaksi masih perlu diuji lebih lanjut.',
            ],
            'assistants' => [
                [
                    'name' => 'AI Coding Assistant',
                    'description' => 'Bantuan implementasi kode dan struktur program.',
                    'prompt' => 'Pada sintak Design and Develop untuk proyek :nama_proyek, bantu saya memetakan struktur form, modul inti, logika transaksi, dan urutan langkah coding yang sebaiknya dikerjakan lebih dulu.',
                    'default_extra_context' => 'Bantu saya membuat kode program dan struktur aplikasi berbasis Pemrograman Visual sesuai fitur yang akan dikembangkan pada proyek ini.',
                ],
                [
                    'name' => 'AI Debugging Assistant',
                    'description' => 'Bantuan menemukan dan memperbaiki error.',
                    'prompt' => 'Saat mengembangkan proyek :nama_proyek pada materi :materi, bantu saya menelusuri error dengan menyusun kemungkinan penyebab, langkah pengecekan, urutan debugging, dan tindakan perbaikan yang paling aman.',
                    'default_extra_context' => 'Bantu saya menemukan dan memperbaiki kesalahan kode program atau error yang muncul pada aplikasi berbasis Pemrograman Visual yang sedang dikembangkan.',
                ],
                [
                    'name' => 'AI Database Assistant',
                    'description' => 'Bantuan desain tabel dan query database.',
                    'prompt' => 'Untuk proyek :nama_proyek, bantu saya menyusun desain database yang mencakup tabel utama, field penting, relasi, validasi data, dan query dasar untuk transaksi serta laporan.',
                    'default_extra_context' => 'Bantu saya merancang database, membuat tabel dan query SQL, serta menghubungkan database dengan aplikasi Pemrograman Visual yang sedang dikembangkan.',
                ],
            ],
        ],
        'R' => [
            'order' => 4,
            'title' => 'Review and Revise',
            'summary' => 'Meninjau dan merevisi',
            'description' => 'Tahap peninjauan kualitas program, pengujian, dan revisi berdasarkan temuan error atau kekurangan desain.',
            'workspace_title' => 'Ruang Kerja Proyek: Review and Revise (R)',
            'workspace_intro' => 'Tinjau hasil proyek, terima umpan balik, dan lakukan revisi untuk penyempurnaan.',
            'color' => '#7342ff',
            'fields' => [
                [
                    'name' => 'hasil_review',
                    'label' => 'Hasil Review *',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'Tuliskan hasil review atau umpan balik utama terhadap proyek...',
                ],
                [
                    'name' => 'kesalahan_kekurangan',
                    'label' => 'Kesalahan / Kekurangan Ditemukan',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Tuliskan kesalahan atau kekurangan yang ditemukan...',
                ],
                [
                    'name' => 'saran_perbaikan',
                    'label' => 'Saran Perbaikan',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Tuliskan saran perbaikan untuk penyempurnaan proyek...',
                ],
                [
                    'name' => 'revisi_dilakukan',
                    'label' => 'Revisi yang Dilakukan',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Tuliskan revisi atau perbaikan yang telah dilakukan...',
                ],
                [
                    'name' => 'hasil_setelah_revisi',
                    'label' => 'Hasil Setelah Revisi',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Jelaskan hasil proyek setelah revisi dilakukan...',
                ],
                [
                    'name' => 'catatan_tambahan',
                    'label' => 'Catatan Tambahan (Opsional)',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Tuliskan catatan tambahan terkait tahap ini...',
                ],
            ],
            'assistants' => [
                [
                    'name' => 'AI Feedback Assistant',
                    'description' => 'Bantuan evaluasi dan umpan balik terhadap hasil proyek.',
                    'prompt' => 'Untuk proyek :nama_proyek pada sintak Review and Revise, bantu saya menyusun umpan balik terhadap hasil proyek dengan menyorot kekuatan, kelemahan, dan prioritas perbaikan.',
                    'default_extra_context' => 'Bantu saya mengevaluasi hasil proyek aplikasi yang telah dikembangkan serta berikan umpan balik dan saran perbaikan terhadap fitur, tampilan, dan fungsi aplikasi.',
                ],
                [
                    'name' => 'AI Revision Assistant',
                    'description' => 'Bantuan revisi dan penyempurnaan aplikasi hasil evaluasi proyek.',
                    'prompt' => 'Untuk proyek :nama_proyek, bantu saya merumuskan revisi yang paling prioritas berdasarkan hasil evaluasi, dampak ke pengguna, dan langkah implementasi perbaikannya.',
                    'default_extra_context' => 'Bantu saya melakukan revisi dan penyempurnaan aplikasi berdasarkan hasil evaluasi dan umpan balik yang telah diperoleh pada tahap review proyek.',
                ],
            ],
        ],
        'U' => [
            'order' => 5,
            'title' => 'Utilize and Present',
            'summary' => 'Mengimplementasikan dan mempresentasikan',
            'description' => 'Mahasiswa menyiapkan produk untuk demo, menyusun alur presentasi, dan menonjolkan manfaat solusi yang dibuat.',
            'workspace_title' => 'Ruang Kerja Proyek: Utilize and Present (U)',
            'workspace_intro' => 'Siapkan presentasi dan demonstrasikan hasil proyek aplikasi.',
            'color' => '#2b6cb8',
            'fields' => [
                [
                    'name' => 'judul_presentasi',
                    'label' => 'Judul Presentasi *',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'Tuliskan judul presentasi proyek Anda...',
                ],
                [
                    'name' => 'ringkasan_proyek',
                    'label' => 'Ringkasan Proyek',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Ringkas proyek yang akan dipresentasikan...',
                ],
                [
                    'name' => 'fitur_utama_disampaikan',
                    'label' => 'Fitur Utama yang Disampaikan *',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'Tuliskan fitur utama yang akan Anda tampilkan saat presentasi...',
                ],
                [
                    'name' => 'strategi_demonstrasi',
                    'label' => 'Strategi Demonstrasi',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Jelaskan strategi demonstrasi proyek saat presentasi...',
                ],
                [
                    'name' => 'dokumentasi_presentasi',
                    'label' => 'Dokumentasi Presentasi (Opsional)',
                    'type' => 'file',
                    'required' => false,
                    'helper' => 'Upload / Pilih File (Opsional)',
                ],
                [
                    'name' => 'catatan_tambahan',
                    'label' => 'Catatan Tambahan (Opsional)',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Tuliskan catatan tambahan terkait tahap ini...',
                ],
            ],
            'assistants' => [
                [
                    'name' => 'AI Presentation Assistant',
                    'description' => 'Bantuan penyusunan materi presentasi proyek.',
                    'prompt' => 'Untuk proyek :nama_proyek, bantu saya menyusun materi presentasi yang ringkas, runtut, dan meyakinkan untuk menjelaskan masalah, solusi, fitur, dan hasil proyek.',
                    'default_extra_context' => 'Bantu saya menyusun materi presentasi proyek aplikasi secara sistematis, mulai dari latar belakang, fitur aplikasi, proses pengembangan, hingga hasil implementasi proyek.',
                ],
                [
                    'name' => 'AI Communication Assistant',
                    'description' => 'Bantuan komunikasi dan demonstrasi proyek.',
                    'prompt' => 'Untuk proyek :nama_proyek, bantu saya menyiapkan cara komunikasi dan demonstrasi proyek yang jelas, termasuk narasi demo, poin penting yang harus disampaikan, dan antisipasi pertanyaan audiens.',
                    'default_extra_context' => 'Bantu saya menyiapkan cara menjelaskan dan mendemonstrasikan aplikasi proyek agar penyampaian presentasi lebih jelas, menarik, dan mudah dipahami audiens.',
                ],
            ],
        ],
        'L' => [
            'order' => 6,
            'title' => 'Learn and Reflect',
            'summary' => 'Belajar dan merefleksikan',
            'description' => 'Tahap akhir untuk merekam refleksi belajar, keterampilan yang berkembang, dan langkah perbaikan berikutnya.',
            'workspace_title' => 'Ruang Kerja Proyek: Learn and Reflect (L)',
            'workspace_intro' => 'Refleksikan pengalaman belajar dan evaluasi diri untuk pengembangan berikutnya.',
            'color' => '#f43b7a',
            'fields' => [
                [
                    'name' => 'refleksi_pembelajaran',
                    'label' => 'Pengalaman Belajar *',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'Tuliskan pengalaman belajar paling penting selama mengerjakan proyek...',
                ],
                [
                    'name' => 'kesulitan_belajar',
                    'label' => 'Kesulitan Belajar yang Dihadapi',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Tuliskan kesulitan belajar yang Anda hadapi...',
                ],
                [
                    'name' => 'solusi_dilakukan',
                    'label' => 'Solusi yang Dilakukan',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Jelaskan solusi atau strategi yang Anda lakukan untuk mengatasi kendala...',
                ],
                [
                    'name' => 'capaian_pembelajaran',
                    'label' => 'Capaian Pembelajaran',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Tuliskan capaian pembelajaran yang Anda peroleh dari proyek ini...',
                ],
                [
                    'name' => 'rencana_pengembangan',
                    'label' => 'Rencana Pengembangan',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Tuliskan rencana pengembangan atau tindak lanjut berikutnya...',
                ],
                [
                    'name' => 'catatan_tambahan',
                    'label' => 'Catatan Tambahan (Opsional)',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Tuliskan catatan tambahan terkait tahap ini...',
                ],
            ],
            'assistants' => [
                [
                    'name' => 'AI Reflective Assistant',
                    'description' => 'Bantuan refleksi pembelajaran.',
                    'prompt' => 'Untuk proyek :nama_proyek, bantu saya menulis refleksi pembelajaran yang jujur dan terstruktur tentang pengalaman belajar, tantangan, dan insight terpenting selama proyek.',
                    'default_extra_context' => 'Bantu saya melakukan refleksi terhadap proses pembelajaran dan pengembangan proyek yang telah dilakukan, termasuk capaian, kesulitan, dan strategi perbaikan pembelajaran berikutnya.',
                ],
                [
                    'name' => 'AI Learning Analytics Assistant',
                    'description' => 'Bantuan analisis perkembangan belajar.',
                    'prompt' => 'Untuk proyek :nama_proyek, bantu saya menganalisis perkembangan belajar, keterampilan yang meningkat, area yang masih lemah, dan tindak lanjut yang realistis.',
                    'default_extra_context' => 'Bantu saya menganalisis perkembangan pembelajaran berdasarkan aktivitas proyek, progres sintak, dan kemampuan yang telah saya capai selama pengembangan aplikasi.',
                ],
            ],
        ],
    ],
];